---
title: "datasets"
output: html_document
date: '2022-09-08'
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(janitor)
library(haven)
library(psych)
library(skimr)
library(mdepriv)
library(broom)
library(readxl)
library(widyr)
library(DT)
library(viridis)
library(corrplot)
library(rpart)
library(rpart.utils)
library(rattle)
library(rpart.plot)
library(randomForest)
library(broomstick)
library(patchwork)
library(tidymodels)
library(vip)
library(glmnet)
library(tidytext)
library(flextable)

range01 <- function(x){(x-min(x))/(max(x)-min(x))}
range_wna <- function(x){(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))}

mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

opts <- options(knitr.kable.NA = "")

`%out%` <- Negate(`%in%`)

# disabling scientific notation
options(scipen = 999)

theme_set(theme_light())
```

## Reference datasets

```{r}
pcodes <- read_excel("./data/Myanmar PCodes Release_9.3_Jan2021_(StRgn_Dist_Tsp_Town_Ward_VT).xlsx",
                     sheet = "03_Township") 

conflict_score <-  read_csv("./data/conflict_score_20220920.csv") 

pin <- read_csv("./data/fs_pin.csv") 

```



## MSNA

```{r warning = FALSE}
read_excel("./data/REACH_MSNA 2022_Dataset_with_Weights_External.xlsx", 
         sheet = "HH_dataset") %>%  
  clean_names() %>% 
  mutate(hhfcs_inv = range_wna(112 - fs_calculated_fcs), 
         not_improved_housing = ifelse(
           snfi_sheltertype %in% c("makeshift_shelter",
                                   "unfinished_non_enclosed_building",
                                   "tent",
                                   "dont_know",
                                   "other",
                                   "collective_shelter"), 1, 0), 
         not_improved_water_monsoon = ifelse(
           wash_drinkingwatersource_monsoon %in% c("borehole_tubewell",
                                                   "piped_connection_to_house_or_neighbors_house",
                                                   "public_tapstandpipe",
                                                   "rain_water_collection",
                                                   "protected_well",
                                                   "protected_spring"), 0, 1), 
         not_improved_water_dry = ifelse(
           wash_drinkingwatersource_dry %in% c("borehole_tubewell",
                                                   "piped_connection_to_house_or_neighbors_house",
                                                   "public_tapstandpipe",
                                                   "rain_water_collection",
                                                   "protected_well",
                                                   "protected_spring"), 0, 1), 
         not_improved_water = ifelse(not_improved_water_monsoon == 1 | 
                                       not_improved_water_dry == 1, 1, 0), 
         not_improved_sanitation = ifelse(
           wash_sanitationfacility %in% c("flush_or_pourflush_toilet",
                                         "pit_latrine_with_a_slab_and_platform",
                                         "pit_vip_toilet"), 1, 0), 
         rural = ifelse(ward_village == "ward", 0, 1), 
         concern_violence = ifelse(prot_security_concerns_boys %in% 
                                     c("threatenedviolence",
                                       "detained",
                                       "recruitedarmedgroups",
                                       "injuredexplosive") |
                                     prot_security_concerns_girls %in% 
                                     c("threatenedviolence",
                                       "detained",
                                       "recruitedarmedgroups",
                                       "injuredexplosive") |
                                     prot_security_concerns_women %in% 
                                     c("threatenedviolence",
                                       "detained",
                                       "recruitedarmedgroups",
                                       "injuredexplosive") | 
                                     prot_security_concerns_men %in% 
                                     c("threatenedviolence",
                                       "detained",
                                       "recruitedarmedgroups",
                                       "injuredexplosive"), 
                                   1, 0)) %>% 
   rename(state = state_region_2) %>% 
  write_csv("./data/msna.csv")

  
```


## FAO/WFP 

```{r}

survey <- read_csv("./data/survey3.csv") %>% 
  mutate(rcsi = 
           r_csi_less_qlty * 1 + 
           r_csi_borrow * 2 + 
           r_csi_meal_nb * 1 + 
           r_csi_meal_size * 1 + 
           r_csi_meal_adult * 3, 
         rcsi_range = range_wna(rcsi))

survey_mini <- survey %>%
  mutate(
    edu_higher = ifelse(hoh_education == "edu_higher", 1, 0),
    edu_low = ifelse(hoh_education %in% c ("edu_none", "edu_primary"), 1, 0),
    edu_primary = ifelse(hoh_education == "edu_primary", 1, 0),
    edu_secondary = ifelse(hoh_education == "edu_secondary", 1, 0),
    # edu_religious = ifelse(hoh_education ==  "edu_religious", 1, 0), 
    hh_debt = case_when(hh_debt_borrow_from %in% c(1, 2) ~ 0, 
                        hh_debt_borrow_from %in% c(3, 4, 5, 6, 7, 8, 9) ~ 1, 
                        TRUE ~ 0)) %>%
  select(
    ims_farmer,
    ims_other, 
    ims_public_em, 
    ims_stable_ag, 
    ims_stable_non_ag, 
    ims_casual_ag,
    ims_casual_non_ag,
    ims_prof_self_em, 
    ims_no_income, 
    shocks_conflict,
    shocks_lostwork,  
    shocks_foodprices, 
    shocks_cantworkbusiness,
    shocks_accesseconomy, 
    no_accessmarket,
    edu_higher,
    edu_secondary,
    edu_primary,
    edu_low,
    rural,
    children_0_4,
    hoh_female,
    fies_ateless, fies_fewfoods, fies_healthy, fies_hungry,
    fies_worried, fies_ranout, fies_whlday, fies_skipped,
    fcs_stap, fcs_pulse, fcs_dairy, fcs_pr,
    fcs_veg, fcs_fruit, fcs_fat, fcs_sugar, 
    fcs_borderline_poor, 
    rcsi, 
    cs_stress_hh_assets,
    cs_stress_spent_savings,
    cs_stress_credit,
    cs_stress_borrowed_money,
    cs_crisis_sold_prod_assets,
    cs_crisis_no_school,
    cs_crisis_reduced_health_exp,
    cs_crisis_childwork,
    cs_crisis_consumed_seed_stocks,
    cs_emergency_sold_house,
    cs_emergency_hh_risk,
    cs_emergency_sold_last_draught,
    cs_emergency_hh_migration, 
    hh_debt_more,
    survey_id, 
    agri_hhd, 
    hh_size, 
    no_accessmarket, 
    not_improved_drinking_water, 
    tot_income,
    income_reduced, 
    covid_goodstransp, 
    covid_marketclosed
  ) %>%
  mutate(across(where(is.numeric), ~ replace(., is.na(.), 0))) 

```

```{r}
survey %>% glimpse()
  select(state)
  
```

